apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bkf9oaacr-nodejs
  janus-idp.io/tekton: bkf9oaacr-nodejs
  backstage.io/kubernetes-id: bkf9oaacr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bkf9oaacr-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
