apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bkf9oaacr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bkf9oaacr-nodejs 
  name: bkf9oaacr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bkf9oaacr-nodejs 
